project_name: "Lmk to Text"
mode: "train"
pretrain_model: ~
exp_dir: "exp_lmk2t"
exp_num: "000"
save_step: 1
valid_step: 1

epoch: 500
batch_size: 128
num_workers: 12
resolution: 256
lmk2lip_lr: 0.0001
lmk2lip_gamma: 0.999
lip2t_lr: 0.0001
lip2t_gamma: 0.999
gpu: True
wandb: True
batch_first: True
ddp_flag: False

class_lambda: 5.0
triplet_lambda: 1.0

train_list: "metadata/LRW_train_3090.txt"
val_list: "metadata/LRW_val_3090.txt"
test_list: "metadata/LRW_test_3090.txt"
max_size: 0
lip_emb: 256
lmk_emb: 40
triplet_margin: 1.0