project_name: "SyncNet_wav2lip"
mode: "train"
#pretrain_model: "pretrain_model/LRW_multi.pth"
pretrain_model: "/home/u2020104180/project/AVsync/pretrain_model/lipsync_expert.pth"
#pretrain_model: ~
exp_dir: "exp_syncnet_wav2lip"
exp_num: "000"
save_step: 1
valid_step: 1

epoch: 100
batch_size: 64
num_workers: 16
sync_lr: 0.00039
sync_gamma: 0.99
gpu: True
wandb: False

#train_list:  "metadata/LRS2_train.txt"
#val_list:      "metadata/LRS2_val.txt"
#test_list:    "metadata/LRS2_test.txt"
train_list:  "metadata/train.txt"
val_list:    "metadata/val.txt"
test_list:   "metadata/test.txt"
img_size: 112
lip_emb: 256
voice_emb: 256
tgt_frame_num: 5
tgt_fps: 25

preemphasize: True
preemphasis: 0.97
min_level_db: -100
ref_level_db: 20
fmin: 55
fmax: 7600

num_mels: 80
rescale: True
rescaling_max: 0.9
use_lws: False
n_fft: 800
hop_size: 200
win_size: 800
sample_rate: 16000
frame_shift_ms: ~
signal_normalization: True
allow_clipping_in_normalization: True
symmetric_mels: True
max_abs_value: 4.
