project_name: "Multisensory"
mode: "train"
pretrain_model: "pretrain_model/LRW_multi.pth"
exp_dir: "exp_multi"
exp_num: "000"
save_step: 1
valid_step: 1

epoch: 1000
batch_size: 8
num_workers: 8
sync_lr: 0.00009
sync_gamma: 0.99
gpu: True
wandb: False

class_lambda: 5.0
triplet_lambda: 1.0

#train_list: "metadata/LRW_train_3090.txt"
#val_list: "metadata/LRW_val_3090.txt"
#test_list: "metadata/LRW_test_3090.txt"
#train_list: "metadata/LRW_train_3090_train.txt"
#val_list:     "metadata/LRW_train_3090_val.txt"
#test_list:   "metadata/LRW_train_3090_test.txt"
train_list:  "metadata/avspeech_train.txt"
val_list:      "metadata/avspeech_val.txt"
test_list:    "metadata/avspeech_test.txt"
#train_list: "metadata/lab_train_3090.txt"
#val_list:   "metadata/lab_val_3090.txt"
#test_list:  "metadata/lab_test_3090.txt"
#img_size: [1280,720]
img_size: 720
face_size: 160
max_size: 0
lip_emb: 256
voice_emb: 256
lmk_emb: 40
n_mfcc: 0
seq_len: 15

margin: 1.0
stride: 2
