project_name: "Audio Video Synchronization"
mode: "train"
pretrain_model: "pretrain_model/pre_av.model"
exp_dir: "exp_train"
exp_num: "000"
save_step: 1
valid_step: 1

epoch: 1000
batch_size: 512
num_workers: 12
resolution: -1
lmk2lip_lr: 0.0001
lmk2lip_gamma: 0.99
wav2v_lr: 0.0001
wav2v_gamma: 0.99
sync_lr: 0.0003
sync_gamma: 0.99
gpu: True
wandb: False
batch_first: True

class_lambda: 5.0
triplet_lambda: 1.0

train_list: "metadata/LRW_train_3090.txt"
val_list: "metadata/LRW_val_3090.txt"
test_list: "metadata/LRW_test_3090.txt"
max_size: 0
lip_emb: 256
voice_emb: 256
lmk_emb: 40
n_mfcc: 0
seq_len: 29
triplet_margin: 1.0
